package com.aspiring_creators.aichopaicho.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val Primary = Color(0xFF006C4C)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF89F8C6)
val OnPrimaryContainer = Color(0xFF002114)
val Secondary = Color(0xFF4C6358)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFCEE9DA)
val OnSecondaryContainer = Color(0xFF092017)
val Tertiary = Color(0xFF3F6374)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFC3E8FC)
val OnTertiaryContainer = Color(0xFF001F2A)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF410002)
val Background = Color(0xFFFBFDFA)
val OnBackground = Color(0xFF191C1B)
val Surface = Color(0xFFFBFDFA)
val OnSurface = Color(0xFF191C1B)
val SurfaceVariant = Color(0xFFDBE5DE)
val OnSurfaceVariant = Color(0xFF404944)
val Outline = Color(0xFF707974)

// Dark Theme
val PrimaryDark = Color(0xFF6CDBAB)
val OnPrimaryDark = Color(0xFF003825)
val PrimaryContainerDark = Color(0xFF005138)
val OnPrimaryContainerDark = Color(0xFF89F8C6)
val SecondaryDark = Color(0xFFB3CCBE)
val OnSecondaryDark = Color(0xFF1E352B)
val SecondaryContainerDark = Color(0xFF344C41)
val OnSecondaryContainerDark = Color(0xFFCEE9DA)
val TertiaryDark = Color(0xFFA7CCE0)
val OnTertiaryDark = Color(0xFF0B3544)
val TertiaryContainerDark = Color(0xFF264B5C)
val OnTertiaryContainerDark = Color(0xFFC3E8FC)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF191C1B)
val OnBackgroundDark = Color(0xFFE1E3DF)
val SurfaceDark = Color(0xFF191C1B)
val OnSurfaceDark = Color(0xFFE1E3DF)
val SurfaceVariantDark = Color(0xFF404944)
val OnSurfaceVariantDark = Color(0xFFBFC9C2)
val OutlineDark = Color(0xFF8A938D)

// Custom Colors
val LentColor = Color(0xFF2E7D32) // Green for money coming in (asset)
val BorrowedColor = Color(0xFFC62828) // Red for money owed (liability)
val PaidColor = Color(0xFF388E3C)
val PartiallyPaidColor = Color(0xFFF57C00)

